version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g @angular/cli
      - npm install

  build:
    commands:
      - ng build --configuration=production
      - cp appspec.yml dist/
      - mkdir -p dist/scripts
      - cp scripts/install_dependencies.sh dist/scripts/

artifacts:
  files:
    - '**/*'
  base-directory: dist

